# Generated by Django 3.2.8 on 2021-10-30 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_date', models.DateTimeField(verbose_name='price date')),
                ('security_name', models.CharField(max_length=140)),
                ('ticker', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('securities', models.ManyToManyField(to='contests.Security')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.IntegerField(default=7)),
                ('entry_fee', models.DecimalField(decimal_places=4, max_digits=6)),
                ('num_contestants', models.IntegerField(default=2)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('title', models.CharField(max_length=200)),
                ('security_pool_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contests.securitypool')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
