# Generated by Django 3.2.8 on 2021-10-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(default=None, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=None, verbose_name='start date'),
        ),
    ]
