# Generated by Django 3.2.8 on 2021-10-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20211030_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='contest',
            name='security_pool_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contests.securitypool'),
        ),
    ]
