# Generated by Django 3.2.8 on 2021-11-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20211030_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='security_pool_id',
            new_name='secpool_id',
        ),
        migrations.RemoveField(
            model_name='securitypool',
            name='end_price',
        ),
        migrations.RemoveField(
            model_name='securitypool',
            name='start_price',
        ),
        migrations.AddField(
            model_name='contest',
            name='sec_end_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contest',
            name='sec_start_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contest',
            name='num_contestants',
            field=models.IntegerField(default=1),
        ),
    ]
