# Generated by Django 3.2.8 on 2021-11-06 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20211106_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitypool',
            old_name='securities',
            new_name='security',
        ),
        migrations.AlterField(
            model_name='contest',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2021, 11, 6), verbose_name='start date'),
        ),
    ]
